[project]
name = "raspberry-rover"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "faster-whisper>=1.2.1",
    "openwakeword==0.6.0",
    "picamera2>=0.3.36",
    "piper-tts>=1.6.1",
    "pyaudio>=0.2.14",
    "silero-vad>=6.2.1",
    "ultralytics>=8.4.115",
]

[build-system]
requires = ["uv_build>=0.9.0,<0.13"]
build-backend = "uv_build"

[tool.uv]
exclude-dependencies = ["tflite-runtime"]

[tool.uv.build-backend]
module-name = "robot"
